# frozen_string_literal: true

require_relative 'support/test_runner'

desc 'Run all sample suites and fail if any suite fails'
task :test do
  SampleTestRunner.run(Dir[File.join(__dir__, 'sample_app[1-6]')].sort)
end

task default: :test
